# Generated by Django 4.1.3 on 2022-11-25 15:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('value', models.PositiveIntegerField()),
                ('cpf', models.CharField(max_length=11)),
                ('card', models.CharField(max_length=12)),
                ('time', models.TimeField()),
                ('owner', models.TextField(max_length=14)),
                ('store', models.TextField(max_length=19)),
            ],
        ),
    ]
