# Generated by Django 4.1.3 on 2022-11-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='type',
            field=models.CharField(choices=[(1, 'Debito'), (2, 'Boleto'), (3, 'Financiamento'), (4, 'Credito'), (5, 'Recebimento Emprestimo'), (6, 'Vendas'), (7, 'Recebimento TED'), (8, 'Recebimento DOC'), (9, 'Aluguel')], default=1, max_length=1),
        ),
    ]
